### ISSUE TITLE
Impersonation Glitch

### ISSUE THREAD

**Issue by nanepiwo** [kaeza/minetest-irc#15]
Having the nick "IRC" can impersonate others. For example , typing "<kaeza> glitched" from the nick "IRC" will show as "<kaeza@IRC> glitches" in-game. I believe this can be fixed if messages from this nick are ignored, similarly to how messages from the server are ignored (Ex. If someone from IRC types "MT-Server, players", the people in-game do not see the list.

**Comment by thatgraemeguy** [comment]
I don't understand where impersonation is coming into this. Are you referring to the in-game chat or IRC chat? Where is the message typed in this scenario? What is the person's IRC nick or in-game name? What is the server's name for IRC purposes?

**Comment by ShadowNinja** [comment]
@thatgraemeguy
IRC:
```
* kaeza glitches
-- OR --
<IRC> * kaeza glitches
```
Results in:
```
* kaeza@IRC glitches
```
in-game.

**Comment by nanepiwo** [comment]
Also

<kaeza> glitches.
--- OR ---
<IRC> <kaeza> glitches.

Results in:

<kaeza@IRC> glitches.

in-game.

Note that, on InchraNet, 0gb.us owns the nick "IRC" and has it enforced, but this mod should still ignore messages from that nick.

**Comment by thatgraemeguy** [comment]
So this scenario revolves around the server using "IRC" as its nick?

Sorry, it wasn't really clear at all.

**Comment by nanepiwo** [comment]
No, a user on IRC using the nick IRC.

**Comment by thatgraemeguy** [comment]
They would appear as "IRC@IRC" if you were in game. Who's is being impersonated in this case?

**Comment by nanepiwo** [comment]
But if that nick types "<nanepiwo> Hi" that would show as "<nanepiwo@IRC> hi". This is because of a feature. If my nick on irc is nanepiwo and I type "<Admin> hi" that would be <Admin@nanepiwo> hi"

**Comment by ShadowNinja** [comment]
30fa81a3abdabd3382b497b53d7f0c923a058c3f
